// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyys9dNCNSSGiWeAJWXAZ3Bwtj4NOeVZ4',
    appId: '1:393332053422:web:9c51e9e5ba515631d4643f',
    messagingSenderId: '393332053422',
    projectId: 'rexvin-leads-syste',
    authDomain: 'rexvin-leads-syste.firebaseapp.com',
    databaseURL: 'https://rexvin-leads-syste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rexvin-leads-syste.appspot.com',
    measurementId: 'G-HYL89TR7M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY2MEwukPAeImg-z83K6JGmomYF_y_DRI',
    appId: '1:393332053422:android:60f6e7461bb70290d4643f',
    messagingSenderId: '393332053422',
    projectId: 'rexvin-leads-syste',
    databaseURL: 'https://rexvin-leads-syste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rexvin-leads-syste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpokSTc0McZuhcE8O960dSWftATCdtwlI',
    appId: '1:393332053422:ios:f4e06ab06a3ca13ad4643f',
    messagingSenderId: '393332053422',
    projectId: 'rexvin-leads-syste',
    databaseURL: 'https://rexvin-leads-syste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rexvin-leads-syste.appspot.com',
    iosBundleId: 'com.example.rels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpokSTc0McZuhcE8O960dSWftATCdtwlI',
    appId: '1:393332053422:ios:01d1c73561dd525ad4643f',
    messagingSenderId: '393332053422',
    projectId: 'rexvin-leads-syste',
    databaseURL: 'https://rexvin-leads-syste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rexvin-leads-syste.appspot.com',
    iosBundleId: 'com.example.rels.RunnerTests',
  );
}
